name: Qt CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-declarative-dev
          echo "Qt6_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            lcov \
            gcovr

      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} -GNinja -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build project
        run: |
          cd build
          cmake --build . --parallel $(nproc)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --timeout 20

      - name: Generate coverage
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info --ignore-errors unused
          lcov --remove coverage.info \
            '/usr/*' \
            '*/tests/*' \
            '*/tests_autogen/*' \
            '*/CMakeFiles/*' \
            '*.moc' \
            '*.qrc' \
            --output-file coverage.filtered.info
          genhtml coverage.filtered.info \
            --output-directory coverage-report \
            --ignore-errors source \
            --demangle-cpp \
            --legend
          gcovr --xml-pretty --output=coverage.xml --root=${GITHUB_WORKSPACE}

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            build/coverage-report/**
            build/coverage.xml